// Mirror the protobuf package hierarchy so that cross-package references
// generated by tonic-build (e.g. `super::super::node::v1::NodeInfo`)
// resolve correctly.

pub mod gpucluster {
    pub mod node {
        pub mod v1 {
            tonic::include_proto!("gpucluster.node.v1");
        }
    }
    pub mod coordinator {
        pub mod v1 {
            tonic::include_proto!("gpucluster.coordinator.v1");
        }
    }
    pub mod management {
        pub mod v1 {
            tonic::include_proto!("gpucluster.management.v1");
        }
    }
}

// Friendly aliases for downstream crates.
pub use gpucluster::node::v1        as node;
pub use gpucluster::coordinator::v1 as coordinator;
pub use gpucluster::management::v1  as management;
